# environment file fo CI testing
# when xspec is needed
name: test_env
channels:
  - threeml
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytest
  - pytest-cov
  - codecov
  - coverage
  - setuptools
  - numpy>=1.15 
  - scipy>=1.4
  - emcee>=3
  - astropy
  - matplotlib<3.9
  - uncertainties
  - pyyaml>=5.1
  - dill
  - iminuit>=2
  - astromodels>=2
  - astroquery
  - corner>=1.0.2
  - pandas>=0.23
  - requests
  - speclite
  - pymultinest
  - ultranest
  - dynesty>=1
  - pygmo>=2.4
  - ipywidgets
  - ipython
  - ipyparallel
  - numba
  - xz
  - py
  - numexpr
  - ipopt
  - numdifftools
  - tqdm
  - future
  - colorama
  - omegaconf
  - flake8
  - reproject
  - uproot
  - awkward
  - hist
  - mplhep
  - joblib
  - h5py
  - rich