# environment file fo CI testing

name: test_env
channels:
  - conda-forge
  - threeml
  - xspecmodels
  - fermi
  - defaults
  - fermi  
dependencies:
  - pip
  - pytest
  - pytest-cov
  - coverage
  - setuptools
  - python
  - numpy>=1.15 
  - scipy>=0.18
  - emcee>=3
  - astropy>=1.0.3
  - matplotlib
  - uncertainties
  - pyyaml>=5.1
  - dill
  - iminuit>=1.2,<2
  - astromodels>=2
  - astroquery
  - corner>=1.0.2
  - pandas>=0.23
  - requests
  - speclite
  - pymultinest
  - ultranest
  - dynesty>=1
  - pygmo>=2.4
  - ipywidgets
  - ipython
  - ipyparallel
  - numba
  - xz
  - py
  - pytest
  - numexpr
  - ipopt
  - numdifftools
  - tqdm
  - astromodels
  - future
  - xspec-modelsonly==6.25
  - fermitools
  - fermipy
  - colorama
