# environment file fo CI testing

name: test_env
channels:
  - conda-forge
  - threeml
  - fermi
  - defaults
dependencies:
  - pip
  - pytest
  - pytest-cov
  - codecov
  - coverage
  - setuptools
  - numpy>=1.15 
  - scipy>=0.18
  - emcee>=3
  - astropy==3.2.3
  - matplotlib
  - uncertainties
  - pyyaml>=5.1
  - dill
  - iminuit>=2
  - astromodels>=2
  - astroquery<=0.4.3
  - corner>=1.0.2
  - pandas>=0.23
  - requests
  - speclite
  - pymultinest
  - ultranest
  - dynesty>=1
  - pygmo>=2.4
  - ipywidgets
  - ipython
  - ipyparallel
  - numba
  - xz
  - py
  - numexpr
  - ipopt
  - numdifftools
  - tqdm
  - future
  - fermitools>=2
  - fermipy>=1
  - colorama
  - omegaconf
  - asciitree
  - flake8
  - root==6.22.2 # [linux]
  - clhep==2.4.4.1
