# environment file fo CI testing

name: test_env
channels:
  - conda-forge
  - threeml
  - fermi
  - defaults
dependencies:
  - pip
  - pytest
  - pytest-cov
  - codecov
  - coverage
  - setuptools
  - numpy>=1.15 
  - scipy>=1.4
  - emcee>=3
  - astropy
  - matplotlib
  - uncertainties
  - pyyaml>=5.1
  - dill
  - iminuit>=2
  - astromodels>=2
  - astroquery
  - corner>=1.0.2
  - pandas>=0.23
  - requests
  - speclite
  - multinest
  - pymultinest
  - ultranest
  - dynesty>=1
  - pygmo>=2.4
  - ipywidgets
  - ipython
  - ipyparallel
  - numba<0.59
  - xz
  - py
  - numexpr
  - ipopt
  - numdifftools
  - tqdm
  - future
  - fermitools>=2
  - colorama
  - omegaconf
  - flake8
